#!/bin/bash

# The password is "password=H6w!@two"
echo -n "password=H6w!@two" > 101-password
if ./crackme3 $(cat 101-password)
then
	echo "Congratulations!"
else
	echo "wrong password."
fi

# cleaning up
rm 101-password 
